### ISSUE TITLE
datastore date mismatch

### ISSUE THREAD

**Issue by viorelsfetea** [Trii/NoseGAE#14]
Hi,

I have a test that writes some entries to the datastore and then deletes all the entries that have been written in the past 5 minutes based on a ndb.DateTimeProperty with auto_now_add set to True. If I run a test that writes to the datastore it will set the DateTimeProperty using the UTC time. However, if right after writing to the datastore, I use the datetime.datetime.now() function it will get the date based on my computers timezone (in my case, that's UTC + 2).

Test:
```python
def test_gae(self):

        TaskTrack(id="Test id",
                  snapshot=self.snapshot.key,
                  process="Test",
                  queue="Queue name").put()

        get_query = TaskTrack.query(
            TaskTrack.process == "Test"
        ).fetch()

        print get_query
        print datetime.now()
```

This outputs:

```
[TaskTrack(key=Key('TaskTrack', 'Test id'), enqueued_at=datetime.datetime(2015, 2, 3, 9, 42, 13, 383950), process=u'Test', queue=u'Queue name', snapshot=Key('Snapshot', 20))]

2015-02-03 11:42:13.389502
```

As far as I can tell, using UTC is intended behavior for dev_appserver2.py and the environment should have inherited, but doesn't (please see below a piece of code from dev_appserver2.py). What am I missing?

```python
def main():
  shutdown.install_signal_handlers()
  # The timezone must be set in the devappserver2 process rather than just in
  # the runtime so printed log timestamps are consistent and the taskqueue stub
  # expects the timezone to be UTC. The runtime inherits the environment.
  os.environ['TZ'] = 'UTC'
  if hasattr(time, 'tzset'):
    # time.tzet() should be called on Unix, but doesn't exist on Windows.
    time.tzset()
  options = PARSER.parse_args()
  dev_server = DevelopmentServer()
  try:
    dev_server.start(options)
    shutdown.wait_until_shutdown()
  finally:
    dev_server.stop()
```

This is my model:

```python
class TaskTrack(BaseModel):
    enqueued_at = ndb.DateTimeProperty(auto_now_add=True)
    snapshot = ndb.KeyProperty(kind=Snapshot)
    process = ndb.StringProperty()
    queue = ndb.StringProperty(required=True)
```

**Comment by Trii** [comment]
I have some similar tests using `auto_add_now` and `datetime.now` and I do not experience that behavior. I will review it today and see if I can resolve it. I am sure that I can set TZ in the plugin initialization and resolve it that way.

**Comment by viorelsfetea** [comment]
I can confirm that fixes the problem, but I'm not sure if it raises problems in testing apps that are somehow timezone sensitive?

**Comment by Trii** [comment]
I did a quick test on my system where I do not have the `TZ` environment variable set but my local time is America/New_York.

```python
    def test_datetime(self):
        from google.appengine.ext import ndb
        from datetime import datetime
        class TZTest(ndb.Model):
            the_time = ndb.DateTimeProperty(auto_now_add=True)

        me = TZTest()
        me.put()

        self.assertLess(me.the_time, datetime.now())
```

Here are the results:
```
======================================================================
FAIL: test_datetime (tests.test_timezone)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Josh/Developer/nosegae_examples/tests/test_timezone.py", line 250, in test_datetime
    self.assertLess(me.the_time, datetime.now())
AssertionError: datetime.datetime(2015, 2, 3, 15, 19, 55, 163368) not less than datetime.datetime(2015, 2, 3, 10, 19, 55, 165160)
```

In my own testing, I use [fixture](https://github.com/fixture-py/fixture) for setting up test data instead of adding entities directly. That way the data is removed for me once my tests are complete.

That being said, the `TZ` issue needs to be resolved because any date or time objects created by the appengine framework would be UTC while your own objects would be whatever local time your system was set to.

**Comment by Trii** [comment]
0.4.1 release has resolved this issue. Thanks for alerting me to it.
