### ISSUE TITLE
Fails to understand type of a class

### ISSUE THREAD

**Issue by esseti** [Trii/NoseGAE#31]
I posted on stackoverflow, i guess it's a problem of this plugin (not sure though)
or maybe it's me that i import incorrectly the two classes where i've the apis (mapped on differents urls)

http://stackoverflow.com/questions/28887093/nosetest-with-gae-fails-where-unitest-pass

**Comment by esseti** [comment]
It may depend on the order of the test cases  http://pastebin.com/1kJcNj1W (pass) http://pastebin.com/YY9fhrVU (fail)

**Comment by Trii** [comment]
I commented on your SO post. The recommended way to check would be with `isinstance()` per the documentation on [type()](https://docs.python.org/2/library/functions.html#type)

Try that out and then let me know. If it doesn't resolve it, I can take a deeper look.

**Comment by esseti** [comment]
indeed the if is based on isinstance and it fails. which makes no sense.

**Comment by Trii** [comment]
Could you give me a quick rundown of how to pull your project and run it locally so I can run your tests and check out the failure?

Also as of 0.4.0, NoseGAE sets up a testbed for you so you do not need to do it in your base test class.

**Comment by esseti** [comment]
i guess it's just 3 steps:

- pull the repository https://github.com/gymcentral/gymcentral

- create a file `cfg.py` in the main folder

<pre> 
API_CACHE_MAX_AGE = 86400
AUTH_TOKEN_MAX_AGE = 86400 * 7 * 3
MODEL_NAME = 'model'
DEBUG = True
PAGE_SIZE = 10
if DEBUG:
    APPIDS_COACH = ['coach-test']
    APPIDS_TRAINEE =['trainee-test']
else: # pragma: no cover
    APPIDS_COACH = []
    APPIDS_TRAINEE = []

API_APP_CFG = {
    'gc': {
        # DO NOT SHARE!!!
        'SECRET_KEY': "123",
        'dpd-ssh-key': "XX"
    }
}<pre> 

- install the requirements (if needed)

then u run the test. note that the test that is not in `test.py` passes. while if u use this code http://pastebin.com/YY9fhrVU it fails.

if you have problems pls contact me sto stefano.tranquillini@gmail.com

**Comment by esseti** [comment]
Hello, did u manage to run the code/replicate the problem?

**Comment by Trii** [comment]
I did not yet. My 9-5 job has been busy. Could you give me step-by-step instructions on how to build your project and make the tests fail. Assume I know nothing about your codebase because I do not.

Shell commands starting from `git clone ...` would be preferred. It would really help me troubleshoot your issue since `nosegae` doesn't do anything with appengine code other than parse your yaml and init testbed stubs

**Comment by esseti** [comment]
Thanks for the support. i'll create a script to allow you to execute everything in one click. as soon as i've i'll post it here.

**Comment by Trii** [comment]
Thanks! That will help a lot.

**Comment by Trii** [comment]
Also check out this post http://stackoverflow.com/questions/9006740/isinstance-and-type-equivelence-failure-due-to-import-mechanism-python-djan

It mentions django in the title but the crux of the issue is importing from paths causing mismatches

**Comment by esseti** [comment]
I may found the problem. if my test.py file is in the root of the project it brakes, if it's in the folder tests it works.
this is the script if u want to try it out (tested on mac)
`#!/bin/bash
git clone https://github.com/gymcentral/gymcentral.git
cd gymcentral
# maybe create the virtualenv here
# install the requriemntes
pip install -r requirements.txt
git submodule init
git submodule update
curl https://gist.githubusercontent.com/esseti/7f3287166b662bbc470e/raw/00065f3adf1741a16162ae2fc1a692c7849835a3/gistfile1.txt -o cfg.py
# this is unitest, and all the test passes

#this is nose and the first passes
nosetests --with-gae tests/test2.py:APITestCases.test_that_fails
#this fails
nosetests --with-gae test2.py:APITestCases.test_that_fails
`
