### ISSUE TITLE
Can't test functions wrapped in @ndb.transactional

### ISSUE THREAD

**Issue by sprt** [Trii/NoseGAE#38]
The test runner just hangs.

**Comment by sadovnychyi** [comment]
Don't think that there's a problem. I have a lot of transactional functions -- all of them covered by tests and everything works fine. Multithreading is on.

**Comment by Trii** [comment]
HI @sprt, please provide some runnable code that illustrates the problem and I can take a look.

**Comment by sprt** [comment]
Hmm, yeah, sorry about that. That happened to me a while ago and I found a workaround so I didn't worry about it. I tried to reproduce it today but I couldn't. Must've been something on my end.

**Comment by Trii** [comment]
I'm glad to hear it is resolved though.

**Comment by sprt** [comment]
Okay, I came across the issue again and I can reproduce it.

It happens when:

 1. Caching is disabled.
 2. A test calls `ndb.Key.delete()`.
 3. Any test after that one calls a transactional function (doing this in the same test works fine).

Result: nose just freezes at step 3.

```python
from google.appengine.ext import ndb

ndb.get_context().set_cache_policy(False)

@ndb.transactional
def transactional_func():
    pass

def test_1():
    ndb.Key('foo', 'bar').delete()

def test_2():
    transactional_func()

test_1.nosegae_datastore_v3 = True
test_2.nosegae_datastore_v3 = True
```

```bash
~/myproject $ NOSE_IGNORE_CONFIG_FILES=1 nosetests --with-gae --gae-lib-root=../google_appengine -v test/test_nosegae.py
test.test_nosegae.test_1 ... ok
test.test_nosegae.test_2 ...
```

**Comment by Trii** [comment]
I can recreate it locally. I'm using the following code and it never gets to wrapped `transactional_func`

```python
from google.appengine.ext import ndb

ndb.get_context().set_cache_policy(False)

@ndb.transactional
def transactional_func():
    from nose.tools import pdb
    pdb.set_trace()
    class M(ndb.Model):
        f = ndb.StringProperty()
    m = m(f='test')
    m.put()
    assert m.key.get() is not None
    m.key.delete()

def test_1():
    ndb.Key('foo', 'bar').delete()

def test_2():
    transactional_func()

test_1.nosegae_datastore_v3 = True
test_2.nosegae_datastore_v3 = True
```
```sh
(jj)Josh@kapbook:issue-38-ndb-transactions$ nosetests --with-gae --gae-lib-root ../google-cloud-sdk/platform/google_appengine -v
test.test_1 ... ok
test.test_2 ... ^C
```

**Comment by sprt** [comment]
Looks like putting `ndb.get_context().set_cache_policy(False)` in each function instead solves it (`setUp()` for class tests).

**Comment by Trii** [comment]
You can also use the `setup` attribute of your test function to do the same as a `unittest.setUp`

```python
from google.appengine.ext import ndb

def setup_func():
    """set up test fixtures"""
    ndb.get_context().set_cache_policy(False)

@ndb.transactional
def transactional_func():
    pass

def test_1():
    ndb.Key('foo', 'bar').delete()

def test_2():
    transactional_func()

test_1.nosegae_datastore_v3 = True
test_1.setup = setup_func
test_2.nosegae_datastore_v3 = True
test_2.setup = setup_func
```

results
```
(jj)Josh@kapbook:issue-38-ndb-transactions$ nosetests --with-gae --gae-lib-root ../google-cloud-sdk/platform/google_appengine -v
test.test_1 ... ok
test.test_2 ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.209s

OK
```

**Comment by Trii** [comment]
The gist of this is that nosegae destroys the testbed stubs in between each run so it in effect undoes `ndb.get_context().set_cache_policy(False)`
