### ISSUE TITLE
nose wants to test vendored libraries

### ISSUE THREAD

**Issue by nopdotcom** [Trii/NoseGAE#41]
My app is based on [appengine-flask-skeleton](https://github.com/GoogleCloudPlatform/appengine-flask-skeleton) , which uses [vendoring](https://cloud.google.com/appengine/docs/python/tools/libraries27?hl=en#vendoring) to place third-party libraries in `lib`. NoseGAE seems to search all those libraries for tests. They aren’t designed for nose-style test matching. What can I do to exclude them?

One example of this seems to be Flask’s [`make_test_environ_builder`](https://github.com/mitsuhiko/flask/blob/master/flask/testing.py#L23) which seems to show up in the following run:

```
appengine-flask-skeleton nop$ nosetests --with-gae
EEE............EEEEEEEEEEEEEEEE................EE
======================================================================
ERROR: Creates a new test builder with some application defaults thrown in.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: make_test_environ_builder() takes at least 1 argument (0 given)
```

I’ve attached the full log.
[nosegae-on-skeleton.txt](https://github.com/Trii/NoseGAE/files/40873/nosegae-on-skeleton.txt)

**Comment by Trii** [comment]
That's an unfortunate side effect of the way app engine does vendoring now. You can use `nose` `-I` option to ignore via regex or install a plugin like `nose-exclude` to ignore `lib` completely. The latter is my personal preference.

**Comment by nopdotcom** [comment]
Oh, `nose-exclude` works great. Thank you! At first reading I thought  `nose -I` should have gotten a bite at the whole path.

Now I just need to get JetBrains to fix nose plugins so I can stop monkeypatching a file inside PyCharm.app :–)

**Comment by Trii** [comment]
You and me both. I have to test a lot of my gae projects outside of pycharm now if they use buildout with a custom interpreter.
