### ISSUE TITLE
guide install for newbie

### ISSUE THREAD

**Issue by truonghoangnguyen** [Trii/NoseGAE#44]
It took me 1 hour to install  on  Window

**Comment by Trii** [comment]
You are right that there are no notes on installation. Luckily this is just a regular python library so you should be able to install it via pypi using `pip install nosegae` or manually with `python setup.py install`.

Is there a specific issue you came across installing on Windows?

**Comment by truonghoangnguyen** [comment]
Thanks, no issue at all, but to find  `python setup.py install` command, I do alot of search/reading code...

**Comment by Trii** [comment]
I will update the readme today. This is the standard way to install libraries in Python so keep it in mind as you use other libraries. Good luck!
