### ISSUE TITLE
GAE 1.9.17 release will unfortunately break NoseGAE

### ISSUE THREAD

**Issue by gbin** [Trii/NoseGAE#6]
Hi,

The old deprecated devappserver is finally going away and we noticed that your project is still depending on the internals of it:

old_dev_appserver.ClearAllButEncodingsModules
old_dev_appserver.FakeFile.SetAllowedPaths
old_dev_appserver.HardenedModulesHook
old_dev_appserver.LoadAppConfig
old_dev_appserver.SetupStubs
old_dev_appserver.SetupSharedModules

dev_appserver_main.DEFAULT_ARGS
dev_appserver_main.ARG_CLEAR_DATASTORE
dev_appserver_main.ARG_LOG_LEVEL
dev_appserver_main.ARG_DATASTORE_PATH
dev_appserver_main.ARG_HISTORY_PATH
[...]

Have you looked into porting it to dev_appserver2 ?

gbin from the Google App Engine SDK team.

**Comment by Trii** [comment]
Resolved via #12 and https://github.com/Trii/NoseGAE/tree/0.4.0
